## 书信息
demo:
    profiles: prod
    book:
        name: 《Spring Boot 2.x 核心技术实战 - 上 基础篇》From YMAL-PROD
        writer: 泥瓦匠BYSocket From YMAL-PROD
## 随机属性
user:
    id: ${random.long}
    age: ${random.int[1,200]}
    desc: 泥瓦匠叫做${random.value}
    uuid: ${random.uuid}